### ISSUE TITLE
Move to EcoJulia

### ISSUE THREAD

**Issue by claireh93** [EcoJulia/EcoSISTEM.jl#58]
A few final things to do:
- [x] Set up a project board to keep track of changes
- [x] Sort out ownership in EcoJulia for Claire
- [x] Move the package to EcoJulia

**Comment by richardreeve** [comment]
@tpoisot @gottacatchenall I think we need to have a discussion about how membership / ownership will work in EcoJulia, and who will be allowed to commit and merge PRs, before we move this across - similar issues arise for other packages probably. I'm sure it won't be difficult to work out, but we should get it right now I think...

**Comment by tpoisot** [comment]
@richardreeve agree - I think you should be able push / make PRs / etc, the only thing not in your current role is org management itself. But if it's not sufficient, it's easy to change.

**Comment by gottacatchenall** [comment]
do you want to require code review to merge to the main branch? right now i think you have to be in the EcoJulia org to merge but that's all

**Comment by richardreeve** [comment]
I'm really thinking about what the default rights for EcoJulia membership are (should it just be read, rather than write as currently?), and whether we should set up `-admin` and `-dev` teams for packages or groups of packages.

This doesn't necessarily just apply to this package, but it's how we've managed things in larger development groups before (specifically for EcoSISTEM in fact, where we had 3 members of the `-admin` team which is a child of `-dev`, with 10 members. We are using `EcoSISTEM:dev` in anger for work, *and* we're obviously submitting `EcoSISTEM:main` for publication now too, so we're just a bit cautious about who has permissions to commit to either branch...

**Comment by richardreeve** [comment]
PS We currently require one admin to approve for `dev` merges, and two for `main` merges, but obviously admins can override these settings.

**Comment by tpoisot** [comment]
I like the idea of setting up teams with elevated privileges from some packages

**Comment by richardreeve** [comment]
I guess what I'm proposing is a default `read` rights for EcoJulia, and an `Everyone` team that contains everyone(!), and has write permissions for the docs, and then broken down from there. Something like this?

[![](https://mermaid.ink/img/eyJjb2RlIjoiIGdyYXBoIExSO1xuICAgIHN1YmdyYXBoIEVjb0p1bGlhW0Vjb0p1bGlhLm9yZ11cbiAgICAgICAgRXZbRXZlcnlvbmUgZWoubzp3cml0ZV1cbiAgICBlbmRcblxuICAgIHN1YmdyYXBoIEVjb1tFY29TSVNURU1dXG4gICAgICAgIEVhW0Vjb1NJU1RFTS1hZG1pbiBlczphZG1pbl1cbiAgICAgICAgRWRbRWNvU0lTVEVNLWRldiBlczp3cml0ZV1cbiAgICAgZW5kXG5cbiAgICBFYSAtLT4gRWRcbiAgICBFZCAtLT4gRXZcblxuICAgIHN1YmdyYXBoIERpdltFY29sb2dpY2FsTmV0d29ya3NdXG4gICAgICAgIERhW0Vjb2xvZ2ljYWxOZXR3b3Jrcy1hZG1pbiBlbjphZG1pbl1cbiAgICAgICAgRGRbRWNvbG9naWNhbE5ldHdvcmtzLWRldiBlYjp3cml0ZV1cbiAgICAgZW5kXG5cbiAgICBEYSAtLT4gRGRcbiAgICBEZCAtLT4gRXZcbiAgICBFdiAtLT4gRUpbbWVtYmVycyBFY29KdWxpYTpyZWFkXVxuXG4iLCJtZXJtYWlkIjp7fSwidXBkYXRlRWRpdG9yIjpmYWxzZX0)](https://mermaid-js.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoiIGdyYXBoIExSO1xuICAgIHN1YmdyYXBoIEVjb0p1bGlhW0Vjb0p1bGlhLm9yZ11cbiAgICAgICAgRXZbRXZlcnlvbmUgZWoubzp3cml0ZV1cbiAgICBlbmRcblxuICAgIHN1YmdyYXBoIEVjb1tFY29TSVNURU1dXG4gICAgICAgIEVhW0Vjb1NJU1RFTS1hZG1pbiBlczphZG1pbl1cbiAgICAgICAgRWRbRWNvU0lTVEVNLWRldiBlczp3cml0ZV1cbiAgICAgZW5kXG5cbiAgICBFYSAtLT4gRWRcbiAgICBFZCAtLT4gRXZcblxuICAgIHN1YmdyYXBoIERpdltFY29sb2dpY2FsTmV0d29ya3NdXG4gICAgICAgIERhW0Vjb2xvZ2ljYWxOZXR3b3Jrcy1hZG1pbiBlbjphZG1pbl1cbiAgICAgICAgRGRbRWNvbG9naWNhbE5ldHdvcmtzLWRldiBlYjp3cml0ZV1cbiAgICAgZW5kXG5cbiAgICBEYSAtLT4gRGRcbiAgICBEZCAtLT4gRXZcbiAgICBFdiAtLT4gRUpbbWVtYmVycyBFY29KdWxpYTpyZWFkXVxuXG4iLCJtZXJtYWlkIjp7fSwidXBkYXRlRWRpdG9yIjpmYWxzZX0)

**Comment by richardreeve** [comment]
Obviously this doesn't have to be done package by package, but something like this anyway. I'd personally add Phylo to the Everyone group, and probably Diversity to the EcoSISTEM group. Thoughts welcome...

**Comment by gottacatchenall** [comment]
i think this is all possible through github teams, although i don't have much experience using it

**Comment by richardreeve** [comment]
We’ve done it before for large collaborating groups exactly like this. That’s why I’m suggesting it. I was just wondering if people think it’s overkill or they think there is a better solution. It’s a bit annoying there has to be an “Everyone” group, but there’s no way of setting default permissions higher for some repos without it.

**Comment by gottacatchenall** [comment]
i think it is the right solution--- i think @tpoisot is the only person with permission to make teams within the ecojulia org at the moment

**Comment by richardreeve** [comment]
I can too. Let’s see what he says though.
